# Generated by Django 4.0.4 on 2022-05-05 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta_virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debito',
            fields=[
                ('id_debito', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=110)),
                ('valor_inicial', models.FloatField()),
                ('valor', models.FloatField(default=0, null=True)),
                ('data_transacao', models.CharField(default='05.05.2022 16:38:54', max_length=50)),
                ('cod_conta', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='conta_virtual.contavirtual')),
            ],
        ),
    ]
