# Generated by Django 4.0.4 on 2022-05-05 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaVirtual',
            fields=[
                ('cod_conta', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=30)),
                ('saldo_debito', models.FloatField()),
                ('saldo_credito', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
