# Generated by Django 4.0.4 on 2022-04-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conta_virtual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=110)),
                ('valor', models.FloatField()),
                ('data_trasacao', models.DateTimeField()),
                ('cod_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_virtual.contavirtual')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.FloatField()),
                ('cod_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conta_virtual.contavirtual')),
                ('id_debito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credito.credito')),
            ],
        ),
    ]
