# Generated by Django 4.0.4 on 2022-04-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credito', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credito',
            old_name='data_trasacao',
            new_name='data_transacao',
        ),
    ]
